name: Check Pull Request

on:
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn

      - name: Check dependencies
        run: yarn adio

      - name: Build packages
        run: yarn lerna run build --stream

      - name: Run Jest tests
        run: yarn test
